const SIGNUP = 'SIGNUP';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const ERRORS = 'ERRORS';
const NEW_USER = 'NEW_USER';
const SAVE_USER = 'SAVE_USER';
const SAVE_TOKEN = 'SAVE_TOKEN';
const NEXT_STEP = 'NEXT_STEP';
const PREV_STEP = 'PREV_STEP';
const SAVE_USER_GIFTPACKS = 'SAVE_USER_GIFTPACKS';
const SAVE_USER_GIFTPACKS_WITH_LOCATION = 'SAVE_USER_GIFTPACKS_WITH_LOCATION';
const SAVE_GIFTPACK = 'SAVE_GIFTPACK';
const SAVE_AVAILABLE_GIFTPACKS = 'SAVE_AVAILABLE_GIFTPACKS';
const SET_USER_LOCATION = 'SET_USER_LOCATION';
const LOADING = 'LOADING';
const SUCCESS = 'SUCCESS';
const SAVE_PARTIAL_USER = 'SAVE_PARTIAL_USER';
const SAVE_MEMBERCARDS = 'SAVE_MEMBERCARDS';

export {
	SIGNUP,
	LOGIN,
	LOGOUT,
	ERRORS,
	NEW_USER,
	SAVE_USER,
	SAVE_TOKEN,
	NEXT_STEP,
	PREV_STEP,
	SAVE_USER_GIFTPACKS,
	SAVE_USER_GIFTPACKS_WITH_LOCATION,
	SAVE_GIFTPACK,
	SAVE_AVAILABLE_GIFTPACKS,
	SET_USER_LOCATION,
	LOADING,
	SUCCESS,
	SAVE_PARTIAL_USER,
	SAVE_MEMBERCARDS
};
