const SIGNUP = 'SIGNUP';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const ERRORS = 'ERRORS';
const NEW_USER = 'NEW_USER';
const SAVE_USER = 'SAVE_USER';
const SAVE_TOKEN = 'SAVE_TOKEN';
const NEXT_STEP = 'NEXT_STEP';
const PREV_STEP = 'PREV_STEP';
const SAVE_USER_GIFTPACKS = 'SAVE_USER_GIFTPACKS';
const SAVE_GIFTPACK = 'SAVE_GIFTPACK';
const SET_USER_LOCATION = 'SET_USER_LOCATION';
const LOADING = 'LOADING';

export {
	SIGNUP,
	LOGIN,
	LOGOUT,
	ERRORS,
	NEW_USER,
	SAVE_USER,
	SAVE_TOKEN,
	NEXT_STEP,
	PREV_STEP,
	SAVE_USER_GIFTPACKS,
	SAVE_GIFTPACK,
	SET_USER_LOCATION,
	LOADING
};
